_target_: evals.datasets.nyu.NYU
train_path: /storage/group/dataset_mirrors/01_incoming/probe3d_nyuv2_navi/nyu_geonet
test_path: /storage/group/dataset_mirrors/01_incoming/probe3d_nyuv2_navi/nyuv2/nyuv2_snorm_all.pkl
image_mean: imagenet
augment_train: True
center_crop: True
