_target_: evals.models.cogvideox_pipeline_based.CogVideoXPipelineBased
model_id: "THUDM/CogVideoX-2b"
output: dense
layer: -1
return_multilayer: false
mode: img_resize
num_frames: 2  # Reduced for memory efficiency
prompt: ""
low_memory_mode: true  # Enable aggressive memory optimizations 