system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
batch_size: 8
probe_from_checkpoint: ""
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: nyu
  - probe: depth_dpt
  - _self_
