system:
  random_seed: 8
  num_gpus: 1
  port: 12355
note: ""
scheduler: "original"
log_path : "logdir"
loss: "angular_loss"
batch_size: 8
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: nyu
  - probe: snorm_dpt
  - _self_
